name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set environment
      run:  source env.source
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.9.0

      
    - name: Install dependencies
      run: make all
      
 
